// Copyright 2024 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics -i LogotipoKFT2023_2.png -f rgb565`

#pragma once

#include <qp.h>

extern const uint32_t gfx_LogotipoKFT2023_2_length;
extern const uint8_t  gfx_LogotipoKFT2023_2[557790];
